JADE-1729 - Update shell scripts to compile and fail, if the model packaging failed.

diff --git a/repackage-ccm-models b/repackage-ccm-models
--- a/repackage-ccm-models
+++ b/repackage-ccm-models
@@ -1,21 +1,12 @@
+mvn clean test
+if [[ "$?" -ne 0 ]] ; then
+  echo 'could not perform tests';
+  exit $rc
+fi
+
 # preserve current directory
-pushd src/main/java/
-
-# create the classes directory if missing
-mkdir -p ../../../classes
-
-# delete previous classes and jar
-\rm -rf ../../../classes/*
-
-# compile POJO classes
-javac -d ../../../classes ccm/models/common/*.java
-javac -d ../../../classes ccm/models/system/justin/*.java
-javac -d ../../../classes ccm/models/system/dems/*.java
-javac -d ../../../classes ccm/models/system/splunk/*.java
-javac -d ../../../classes ccm/utils/*.java
-
 # create jar
-cd ../../../classes
+pushd target/classes/
 jar cvf ccm-models.jar ccm/models/*/*.class ccm/models/*/*/*.class ccm/utils/*.class
 
 # return to current directory
