Improve deploy and monitor scripts

diff --git a/scripts/jade-ccm/redeploy-ccm-accessdedup-processor b/scripts/jade-ccm/redeploy-ccm-accessdedup-processor
--- a/scripts/jade-ccm/redeploy-ccm-accessdedup-processor
+++ b/scripts/jade-ccm/redeploy-ccm-accessdedup-processor
@@ -9,6 +9,12 @@ ns_set="cef5dd"
 image_registry_url=$(oc registry info)
 app="ccm-accessdedup-processor"
 
+$(which docker) > /dev/null 2> /dev/null
+if [ $? -ne 0 ]; then
+    echo "Error.  Docker not found."
+    exit 1
+fi
+
 if [ "$1" = "dev" ]; then
     env="dev"
 elif [ "$1" = "test" ]; then
@@ -50,7 +56,7 @@ version=`cat $version_file | grep V1_0 | cut -d'"' -f2`
 ####################################################################################################
 # 1. Set default logging level
 
-echo 
+echo "Step 1: Setting default logging level ..."
 
 logging_level="INFO"
 
@@ -103,7 +109,15 @@ echo "Step 3: Building processor ..."
 
 pushd ../../$app
 mvn clean package -Dquarkus.package.type=uber-jar -Dquarkus.log.level=$logging_level
-docker build --platform linux/amd64 -t $app .
+
+if [ $env = "local" ]; then
+    # build the image for local deployment
+    docker build -t $app .
+else
+    # build the image for OpenShift deployment
+    ## make sure it is build for the linux x64 platform
+    docker build --platform linux/amd64 -t $app .
+fi
 
 if [ "$?" -ne 0 ]; then
     echo "Error.  Build failed."
@@ -166,8 +180,5 @@ else
     # add deployment labels
     oc -n $ns label deployment $app deployer="$deployer" version="$version"
 
-    echo "Deployment complete."
-    
+    echo "Deployment complete."  
 fi
-
-
